# Crear una imagen de ubuntu con la última versión (latest)
FROM ubuntu:latest 

# Correr un comando en el contenedor para crear un archivo
RUN touch /tmp/hola.txt

# Correr un comando en el contenedor para eliminar un archivo
RUN rm /tmp/hola.txt